FROM node:22-alpine AS builder
WORKDIR /app
COPY src/BE/package*.json ./
RUN npm ci
COPY src/BE/ .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY src/BE/package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
COPY dataset/diem_thi_thpt_2024.csv ./dataset/diem_thi_thpt_2024.csv
COPY src/BE/entrypoint.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh
ENV CSV_PATH=/app/dataset/diem_thi_thpt_2024.csv
EXPOSE 3000
ENTRYPOINT ["./entrypoint.sh"]
